<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vimal" failures="3" tests="46" name="day45.DataProviderAnnotation" time="106.289" errors="0" timestamp="2024-12-30T00:18:26 IST" skipped="0">
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.291"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.715"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.992"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.081"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.972"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="4.217"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.172">
    <failure message="Login failed for valid credentials. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login failed for valid credentials. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at day45.DataProviderAnnotation.loginTest(DataProviderAnnotation.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.079"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.720"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.074"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.284"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.189"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.692"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.110">
    <failure message="Login failed for valid credentials. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login failed for valid credentials. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at day45.DataProviderAnnotation.loginTest(DataProviderAnnotation.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.191">
    <failure message="Login failed for valid credentials. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login failed for valid credentials. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at day45.DataProviderAnnotation.loginTest(DataProviderAnnotation.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.685"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.516"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.963"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.952"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="3.016"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.978"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.119"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.665"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.997"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.729"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.080"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.998"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.749"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.214"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.653"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.056"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.747"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.078"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.706"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.969"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.811"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.966"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.758"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.096"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.016"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="4.414"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.008"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="4.371"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.964"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="2.729"/>
  <testcase classname="day45.DataProviderAnnotation" name="loginTest" time="1.507"/>
</testsuite> <!-- day45.DataProviderAnnotation -->
